### PR TITLE
Excluding runs relation from jurisdiction serialization

### PR DESCRIPTION
**Pull request by evz**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Looks fine to me, but I'll wait for @paultag to merge since he was in convo.

I watch all the OCD repos, so I get alerts for everything.

If it's not merged tomorrow, ping me in this issue.

**Comment by evz** [comment]
:+1:

**Comment by evz** [comment]
@paultag @jpmckinney Any chance I can get this merged today? Looking at getting this all setup for the municipal APIs.

**Comment by paultag** [comment]
Looks great. Thanks! :D

**Comment by evz** [comment]
Cool. Thanks!

**Pull request merged**
