### PR TITLE
expose division_ids in posts listing

### PR DESCRIPTION
**Pull request by fgregg**
Show division ids in listings of posts within an organizations. Allows us to walk from person --> post --> division --> geography

### CODE REVIEW

**Comment by paultag** [comment]
Since you're already eating the JOIN, you might want to either include `post.division.name` too, or use `post.division_id`

**Comment by fgregg** [comment]
hm.. posts.division_id sounds good, but doesn't seem to work

**Comment by fgregg** [comment]
Good idea @paultag .

**Comment by paultag** [comment]
LGTM :+1:

**Comment by paultag** [comment]
Thanks, @fgregg !

**Pull request merged**
