### PR TITLE
Disallow arbitrary arguments in loadmappings, to reflect moving those settings

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by paultag** [comment]
Nice cleanup. Thanks!

**Comment by mileswwatkins** [comment]
These settings are now only in `api.opencivicdata.org/shapefiles/definitions.py` only, not in `api.opencivicdata.org/ocdapi/settings.py`.

**Comment by mileswwatkins** [comment]
@paultag, this'll cause production failure if not used with my PR to the `api.opencivicdata.org` that I'm submitting in a couple minutes. So don't deploy it yet :)

**Comment by paultag** [comment]
Righto!

On Wed, Jun 3, 2015 at 1:49 PM, Miles Watkins <notifications@github.com>
wrote:

> @paultag <https://github.com/paultag>, this'll cause production failure
> if not used with my PR to the api.opencivicdata.org that I'm submitting
> in a couple minutes. So don't deploy it yet :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/imago/pull/58#issuecomment-108544997>.
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by paultag** [comment]
Wait, why's that, those were unused, no?

On Wed, Jun 3, 2015 at 1:50 PM, Paul Tagliamonte <
paultag@sunlightfoundation.com> wrote:

> Righto!
>
> On Wed, Jun 3, 2015 at 1:49 PM, Miles Watkins <notifications@github.com>
> wrote:
>
>> @paultag <https://github.com/paultag>, this'll cause production failure
>> if not used with my PR to the api.opencivicdata.org that I'm submitting
>> in a couple minutes. So don't deploy it yet :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opencivicdata/imago/pull/58#issuecomment-108544997>.
>>
>
>
>
> --
> Paul Tagliamonte
> Software Developer | Sunlight Foundation
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by mileswwatkins** [comment]
They _were_ unused, but his explicitly forbids the `start_date` and `end_date` that were set in `api.opencivicdata.org/ocdapi/settings.py`.

**Pull request merged**
